"""Add version_id_col for optimistic locking

Revision ID: 5342e2a95f25
Revises: 6f1a2b3c4d5e
Create Date: 2026-07-04 04:58:08.698835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5342e2a95f25'
down_revision: Union[str, None] = '6f1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('user_settings', sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'version_id')
    op.drop_column('holdings', 'version_id')
    # ### end Alembic commands ###
