"""feat: UserSettings 모델에 language 컬럼 추가

Revision ID: 57fac21b1d0f
Revises: 7888c60cd7a4
Create Date: 2026-07-20 03:25:54.829911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fac21b1d0f'
down_revision: Union[str, None] = '7888c60cd7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
