"""Refactor to timezone-aware DateTime

Revision ID: 5b86ba90d475
Revises: 7f1c4286ef02
Create Date: 2026-06-09 00:45:49.137392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b86ba90d475'
down_revision: Union[str, None] = '7f1c4286ef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
