"""Add Toss API to UserSettings

Revision ID: 7499935b88ad
Revises: f2a3b4c5d6e7
Create Date: 2026-06-08 20:38:58.405614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7499935b88ad'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('toss_app_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_app_secret', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_account_no', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_verification_status', sa.String(), server_default='unverified', nullable=False))
    op.add_column('user_settings', sa.Column('toss_verified_trade_mode', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'toss_verified_at')
    op.drop_column('user_settings', 'toss_verified_trade_mode')
    op.drop_column('user_settings', 'toss_verification_status')
    op.drop_column('user_settings', 'toss_account_no')
    op.drop_column('user_settings', 'toss_app_secret')
    op.drop_column('user_settings', 'toss_app_key')
    # ### end Alembic commands ###
