"""Refactor credentials to 1:N structure

Revision ID: 7f1c4286ef02
Revises: 7499935b88ad
Create Date: 2026-06-08 21:20:09.607556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1c4286ef02'
down_revision: Union[str, None] = '7499935b88ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('app_secret', sa.String(), nullable=True),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verified_trade_mode', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_settings.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker_name', name='uq_user_broker')
    )
    op.create_index(op.f('ix_broker_credentials_id'), 'broker_credentials', ['id'], unique=False)
# ### DATA MIGRATION ###
    connection = op.get_bind()
    
    # Introspect tables
    meta = sa.MetaData()
    user_settings = sa.Table(
        'user_settings', meta,
        sa.Column('user_id', sa.Integer()),
        sa.Column('kis_app_key', sa.String()),
        sa.Column('kis_app_secret', sa.String()),
        sa.Column('kis_account_no', sa.String()),
        sa.Column('kis_verification_status', sa.String()),
        sa.Column('kis_verified_trade_mode', sa.String()),
        sa.Column('kis_verified_at', sa.DateTime()),
        sa.Column('toss_app_key', sa.String()),
        sa.Column('toss_app_secret', sa.String()),
        sa.Column('toss_account_no', sa.String()),
        sa.Column('toss_verification_status', sa.String()),
        sa.Column('toss_verified_trade_mode', sa.String()),
        sa.Column('toss_verified_at', sa.DateTime())
    )
    
    broker_credentials = sa.Table(
        'broker_credentials', meta,
        sa.Column('user_id', sa.Integer()),
        sa.Column('broker_name', sa.String()),
        sa.Column('app_key', sa.String()),
        sa.Column('app_secret', sa.String()),
        sa.Column('account_no', sa.String()),
        sa.Column('verification_status', sa.String()),
        sa.Column('verified_trade_mode', sa.String()),
        sa.Column('verified_at', sa.DateTime())
    )
    
    results = connection.execute(sa.select(user_settings)).mappings().fetchall()
    for r in results:
        if r['kis_app_key'] or r['kis_verification_status'] == 'verified':
            connection.execute(
                broker_credentials.insert().values(
                    user_id=r['user_id'],
                    broker_name='KIS',
                    app_key=r['kis_app_key'],
                    app_secret=r['kis_app_secret'],
                    account_no=r['kis_account_no'],
                    verification_status=r['kis_verification_status'] or 'unverified',
                    verified_trade_mode=r['kis_verified_trade_mode'],
                    verified_at=r['kis_verified_at']
                )
            )
        if r['toss_app_key'] or r['toss_verification_status'] == 'verified':
            connection.execute(
                broker_credentials.insert().values(
                    user_id=r['user_id'],
                    broker_name='TOSS',
                    app_key=r['toss_app_key'],
                    app_secret=r['toss_app_secret'],
                    account_no=r['toss_account_no'],
                    verification_status=r['toss_verification_status'] or 'unverified',
                    verified_trade_mode=r['toss_verified_trade_mode'],
                    verified_at=r['toss_verified_at']
                )
            )
    # ### END DATA MIGRATION ###

    with op.batch_alter_table('user_settings') as batch_op:
        batch_op.drop_column('kis_verified_trade_mode')
        batch_op.drop_column('toss_verified_at')
        batch_op.drop_column('toss_app_key')
        batch_op.drop_column('toss_verified_trade_mode')
        batch_op.drop_column('toss_app_secret')
        batch_op.drop_column('kis_account_no')
        batch_op.drop_column('kis_app_secret')
        batch_op.drop_column('kis_app_key')
        batch_op.drop_column('toss_account_no')
        batch_op.drop_column('kis_verification_status')
        batch_op.drop_column('toss_verification_status')
        batch_op.drop_column('kis_verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('kis_verified_at', sa.DATETIME(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_verification_status', sa.VARCHAR(), server_default=sa.text("'unverified'"), nullable=False))
    op.add_column('user_settings', sa.Column('kis_verification_status', sa.VARCHAR(), server_default=sa.text("'unverified'"), nullable=False))
    op.add_column('user_settings', sa.Column('toss_account_no', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('kis_app_key', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('kis_app_secret', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('kis_account_no', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_app_secret', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_verified_trade_mode', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_app_key', sa.VARCHAR(), nullable=True))
    op.add_column('user_settings', sa.Column('toss_verified_at', sa.DATETIME(), nullable=True))
    op.add_column('user_settings', sa.Column('kis_verified_trade_mode', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_broker_credentials_id'), table_name='broker_credentials')
    op.drop_table('broker_credentials')
    # ### end Alembic commands ###
