"""add_strategy_type_to_user_settings

Revision ID: 908b777e8294
Revises: de9ac01a6b38
Create Date: 2026-05-31 18:09:55.971641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908b777e8294'
down_revision: Union[str, None] = 'de9ac01a6b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('strategy_type', sa.String(), nullable=False, server_default='regime_switching'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'strategy_type')
    # ### end Alembic commands ###
