"""remove_is_real_enabled

Revision ID: 93ff846b6e0a
Revises: 5b86ba90d475
Create Date: 2026-06-09 03:03:36.737458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ff846b6e0a'
down_revision: Union[str, None] = '5b86ba90d475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'is_real_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('is_real_enabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
