"""Add realized_pnl and return_rate to TradeLog

Revision ID: de9ac01a6b38
Revises: 001_baseline
Create Date: 2026-05-28 21:24:46.970521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9ac01a6b38'
down_revision: Union[str, None] = '001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_logs', sa.Column('realized_pnl', sa.Float(), nullable=True))
    op.add_column('trade_logs', sa.Column('return_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_logs', 'return_rate')
    op.drop_column('trade_logs', 'realized_pnl')
    # ### end Alembic commands ###
