"""Add catalog meta columns

Revision ID: f3579cf7ae49
Revises: 300657aeb25d
Create Date: 2026-07-18 05:47:22.217675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3579cf7ae49'
down_revision: Union[str, None] = '300657aeb25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('regime', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('summary_ko', sa.Text(), nullable=True))
    op.add_column('strategies', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('is_selectable', sa.Boolean(), nullable=True))
    
    # Set defaults
    op.execute("UPDATE strategies SET tier='single', regime='ALL', sort_order=0, is_selectable=1")

    # strategy_c / complex (Gold)
    op.execute("UPDATE strategies SET tier='gold', regime='ALL', sort_order=10, summary_ko='쿨라매기, 차트픽(OBV), 시게루(재무/피라미딩), 비트고수(RSI BB, 선물, MACD), ORB, 성배, 피보나치 등 11대 대가 기법 총결집 완전체' WHERE strategy_type IN ('complex', 'strategy_c')")
    
    # senior_simple (Silver)
    op.execute("UPDATE strategies SET tier='silver', regime='ALL', sort_order=20, summary_ko='복잡한 가감점을 제외하고 상승장 시가 돌파(ORB) 및 하락장 RSI BB + OBV 매집 반등 조건 충족 시 즉시 100점 진입하는 초심플 안정형 전략' WHERE strategy_type='senior_simple'")
    
    # strategy_a (Bronze)
    op.execute("UPDATE strategies SET tier='bronze', regime='ALL', sort_order=30, summary_ko='StockAuto 최초의 방패 원형. 일괄 80점 컷오프, 최초 10% 비중 진입 및 고정형 ATR 트레일링 스탑 적용' WHERE strategy_type='strategy_a'")
    
    # strategy_b (Sandbox)
    op.execute("UPDATE strategies SET tier='sandbox', regime='ALL', sort_order=900, summary_ko='과도기 연구용. 채점 로직 분리, 최초 40% 고비중 진입 및 1.0% 수준의 극단적으로 타이트한 조기 익절선 적용', is_selectable=0 WHERE strategy_type='strategy_b'")
    
    # exploded_c (Sandbox)
    op.execute("UPDATE strategies SET tier='sandbox', regime='ALL', sort_order=910, summary_ko='정찰병 제도를 전면 생략하고 진입 즉시 풀비중(Stage 3)으로 배팅하며, 동적 손절선을 아주 넓게 열어둔 고수익 추구형 전략', is_selectable=0 WHERE strategy_type='exploded_c'")
    
    # qullamaggie
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=100, summary_ko='1번 크리스찬 쿨라매기 단독. 52주 최고가 대비 이격 -2% 이내 근접 + 3연속 상승 양봉 돌파 시 진입, EMA 9/20 정배열 붕괴 시 청산' WHERE strategy_type='qullamaggie'")
    
    # obv_only
    op.execute("UPDATE strategies SET regime='BEARISH', sort_order=110, summary_ko='2번 슈퍼개미 차트픽 단독. 일봉상 주가는 하락/횡보나 OBV 이평선은 뚜렷이 우상향하는 세력의 비밀 매집 포착 시 진입' WHERE strategy_type='obv_only'")
    
    # rsi_bb_only
    op.execute("UPDATE strategies SET regime='BEARISH', sort_order=120, summary_ko='5번 비트고수 RSI 볼밴 단독. RSI가 자체 볼린저 밴드 하단을 뚫고 내려갔다가 안으로 강하게 회귀하는 극단적 과매도 스나이핑' WHERE strategy_type='rsi_bb_only'")
    
    # ema_only
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=130, summary_ko='단기 추세의 정방향 추종. 15분봉상 단기 이평선 정배열(EMA 9 > EMA 20)이 완벽히 유지되는 강세 정추세 탑승 기법' WHERE strategy_type='ema_only'")
    
    # vwap_only
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=140, summary_ko='세력 평균 단가 추종. 당일 주가가 세력의 수급 평단선인 VWAP선 위에서 강하게 지지받고 안착하는 종목만 공략' WHERE strategy_type='vwap_only'")
    
    # orb_only
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=150, summary_ko='토비 크라벨 ORB 단독. 장 개시 직후 최초 5분봉 캔들의 최고가를 대량 거래량으로 뚫어내는 장초반 가속 돌파 공략' WHERE strategy_type='orb_only'")
    
    # rsi2_connors
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=160, summary_ko='래리 코너스 단독. 상승장 속 초단기 과매도가 심화되어 RSI(2)가 10 미만으로 수직 낙하할 때 잡고, 5일선(EMA 5) 돌파 시 익절' WHERE strategy_type='rsi2_connors'")
    
    # bb_squeeze
    op.execute("UPDATE strategies SET regime='NEUTRAL', sort_order=170, summary_ko='존 카터 BB 스퀴즈 단독. 볼밴이 켈트너채널 내부에 들어가 에너지를 응축(Squeeze)한 후, 상방으로 폭발적 돌파 시 추세 탑승' WHERE strategy_type='bb_squeeze'")
    
    # regime_switching
    op.execute("UPDATE strategies SET regime='ALL', sort_order=180, summary_ko='최상위 오케스트레이터. QQQ 이평 정배열 상태(레짐)를 실시간 감시하여 단독 전략들의 기동 여부를 스위칭하는 마스터 기법' WHERE strategy_type='regime_switching'")
    
    # antigravity_surge
    op.execute("UPDATE strategies SET regime='BULLISH', sort_order=190, summary_ko='안티그래비티 수급합성. OBV 지수가 20일 고점을 돌파한 상태(세력 매집)에서, 장초반 15분 이내에 쿨라매기식 거래량 폭발과 함께 3% 이상 급등 시 진입' WHERE strategy_type='antigravity_surge'")
    
    # regime_sniper
    op.execute("UPDATE strategies SET regime='ALL', sort_order=200, summary_ko='상승장 변동성수축. QQQ 상승 레짐 상태에서 볼린저 밴드 폭이 극도로 수축(Squeeze)했다가, 대량 거래량과 함께 밴드 상단을 강하게 돌파하는 찰나를 타격' WHERE strategy_type='regime_sniper'")
    
    # phoenix_bounce
    op.execute("UPDATE strategies SET regime='BEARISH', sort_order=210, summary_ko='주도주 기습낙주반등. 12개월 상대강도가 강한 대장주가 단기 악재로 15분봉 RSI 20 이하의 과매도에 진입 시, 양봉 출현과 함께 OBV가 반등할 때 기습 진입' WHERE strategy_type='phoenix_bounce'")

    # Hide slot strategies (only core_satellite, not the multi_slots)
    op.execute("UPDATE strategies SET is_selectable=0 WHERE strategy_type IN ('core_satellite')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'is_selectable')
    op.drop_column('strategies', 'sort_order')
    op.drop_column('strategies', 'summary_ko')
    op.drop_column('strategies', 'regime')
    op.drop_column('strategies', 'tier')
    # ### end Alembic commands ###
